name: .NET OITAVO TESTE

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./GeekBurger.Products
      
    - name: Build
      run: dotnet publish --no-restore -o ./out /p:Version=2.0.${{ github.run_number }}
      working-directory: ./GeekBurger.Products
      
    - name: Pack
      run: dotnet pack --no-restore -o ./nupkgs /p:Version=2.0.${{ github.run_number }}  
      working-directory: ./GeekBurger.Products

    - name: Tests
      run: dotnet test --no-build --verbosity normal # --no-build porque já compilamos na etapa anterior
      working-directory: ./GeekBurger.Products
      
    - name: Push nuget
      run: dotnet nuget push ./nupkgs/*.nupkg -k ${{ secrets.NUGET_API_KEY}} -s http://nugetfiapdotnet.azurewebsites.net/nuget
      working-directory: ./GeekBurger.Products
